name: Build macOS App

on:
  workflow_dispatch:   # permite ejecutarlo a mano
  push:
    branches: [ "main" ]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build for macOS (DMG + ZIP + APP)
        run: npm run dist:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: digalo-con-monica-mac
          path: dist/**
